
# Esta URL es una variable mágica que Render nos da para conectar internamente la App y la DB
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# Estas líneas son útiles para el desarrollo
# 'update' intentará ajustar las tablas automáticamente si cambias tu código Java
spring.jpa.hibernate.ddl-auto=update
# Nos mostrará en la consola de NetBeans las consultas SQL que se ejecutan
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
